// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Memory usage statistics. Total, Available and Used contain numbers of bytes
 * for human consumption.
 * 
 * The other fields in this struct contain kernel specific values.
 */
export interface VirtualMemoryStat {
    /**
     * Total amount of RAM on this system
     */
    "total": number;

    /**
     * RAM available for programs to allocate
     * 
     * This value is computed from the kernel specific values.
     */
    "available": number;

    /**
     * RAM used by programs
     * 
     * This value is computed from the kernel specific values.
     */
    "used": number;

    /**
     * Percentage of RAM used by programs
     * 
     * This value is computed from the kernel specific values.
     */
    "usedPercent": number;

    /**
     * This is the kernel's notion of free memory; RAM chips whose bits nobody
     * cares about the value of right now. For a human consumable number,
     * Available is what you really want.
     */
    "free": number;

    /**
     * OS X / BSD specific numbers:
     * http://www.macyourself.com/2010/02/17/what-is-free-wired-active-and-inactive-system-memory-ram/
     */
    "active": number;
    "inactive": number;
    "wired": number;

    /**
     * FreeBSD specific numbers:
     * https://reviews.freebsd.org/D8467
     */
    "laundry": number;

    /**
     * Linux specific numbers
     * https://blogs.oracle.com/linux/understanding-linux-kernel-memory-statistics
     * https://www.kernel.org/doc/Documentation/filesystems/proc.txt
     * https://www.kernel.org/doc/Documentation/vm/overcommit-accounting
     * https://www.kernel.org/doc/Documentation/vm/transhuge.txt
     */
    "buffers": number;
    "cached": number;
    "writeBack": number;
    "dirty": number;
    "writeBackTmp": number;
    "shared": number;
    "slab": number;
    "sreclaimable": number;
    "sunreclaim": number;
    "pageTables": number;
    "swapCached": number;
    "commitLimit": number;
    "committedAS": number;
    "highTotal": number;
    "highFree": number;
    "lowTotal": number;
    "lowFree": number;
    "swapTotal": number;
    "swapFree": number;
    "mapped": number;
    "vmallocTotal": number;
    "vmallocUsed": number;
    "vmallocChunk": number;
    "hugePagesTotal": number;
    "hugePagesFree": number;
    "hugePagesRsvd": number;
    "hugePagesSurp": number;
    "hugePageSize": number;
    "anonHugePages": number;
}
