// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetSpeed representa la velocidad de red calculada para una interfaz
 */
export interface NetSpeed {
    "name": string;

    /**
     * bytes por segundo enviados
     */
    "sentBps": number;

    /**
     * bytes por segundo recibidos
     */
    "recvBps": number;
}
