// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as disk$0 from "../github.com/shirou/gopsutil/v4/disk/models.js";

export function GetCpuPerc(): $CancellablePromise<number[] | null> {
    return $Call.ByID(2829539297);
}

export function GetDiskUsage(): $CancellablePromise<disk$0.UsageStat | null> {
    return $Call.ByID(3356686475);
}
