// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface UsageStat {
    "path": string;
    "fstype": string;
    "total": number;
    "free": number;
    "used": number;
    "usedPercent": number;
    "inodesTotal": number;
    "inodesUsed": number;
    "inodesFree": number;
    "inodesUsedPercent": number;
}
