// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface IOCountersStat {
    /**
     * interface name
     */
    "name": string;

    /**
     * number of bytes sent
     */
    "bytesSent": number;

    /**
     * number of bytes received
     */
    "bytesRecv": number;

    /**
     * number of packets sent
     */
    "packetsSent": number;

    /**
     * number of packets received
     */
    "packetsRecv": number;

    /**
     * total number of errors while receiving
     */
    "errin": number;

    /**
     * total number of errors while sending
     */
    "errout": number;

    /**
     * total number of incoming packets which were dropped
     */
    "dropin": number;

    /**
     * total number of outgoing packets which were dropped (always 0 on OSX and BSD)
     */
    "dropout": number;

    /**
     * total number of FIFO buffers errors while receiving
     */
    "fifoin": number;

    /**
     * total number of FIFO buffers errors while sending
     */
    "fifoout": number;
}
